small fixment to the privacy function
Ballsdex-Team/BallsDex-DiscordBot pull request #241
Opened 2024-04-23 08:09 UTC by arrayunderscore

well that should help

2024-04-23 08:29 UTC, flaree requested changes

2024-04-23 08:29 UTC, flaree commented on ballsdex/packages/balls/cog.py
> -        return False
I'd recommend changing it to just 

```py
if interaction.user.id == player_obj.discord_id:
    return True
```

At the top of the function. If the user invoking it is the same as the provided player then there's no need to run any of the checks needed for privacy policy

2024-04-23 08:32 UTC, arrayunderscore commented on ballsdex/packages/balls/cog.py
> -        return False
but how then we will inform that the guy's inventory is private?

2024-04-23 08:37 UTC, flaree commented on ballsdex/packages/balls/cog.py
> -        return False
The if check only runs if the user is the invoking command user, in which it just returns that the inventory is not private

2024-04-23 08:39 UTC, arrayunderscore commented on ballsdex/packages/balls/cog.py
> -        return False
hmm, alr let me do edits rq

2024-04-23 08:46 UTC, flaree commented on ballsdex/packages/balls/cog.py
> -        return False
You didn't read what I said, you need to move that conditional to the start of the method

2024-04-23 08:51 UTC, arrayunderscore commented on ballsdex/packages/balls/cog.py
> -        return False
oh, i'm sorry my bad

2024-04-23 09:24 UTC, arrayunderscore commented on ballsdex/packages/balls/cog.py
> -        return False
here made it the first if statement so it doesn't run anything else later on

2024-04-23 09:25 UTC, flaree requested changes

2024-04-23 09:25 UTC, flaree commented on ballsdex/packages/balls/cog.py
> -        return False
Still haven't addressed what I asked, move the if to line 588 and then put the message and return back in the condition for the deny check

2024-04-23 09:25 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +    if interaction.user.id == player_obj.discord_id:
player_obj was just a placeholder in my suggestion, the actual argument is called player. Apologies for that

2024-05-08 11:58 UTC, flaree approved these changes

2024-05-08 12:01 UTC, merged