Replacing cbtext with countryball.description
Ballsdex-Team/BallsDex-DiscordBot pull request #252
Opened 2024-05-10 18:13 UTC by MaxxMXSZ

Just to balance everything else so it looks the same in anyway

2024-05-19 15:17 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +                f"{countryball.description(include_emoji=True, bot=self.bot, is_trade=True)} "
any reason why is_trade kwarg is set to true?

2024-05-19 15:17 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +                f"{countryball.description(include_emoji=True, bot=self.bot, is_trade=True)} "
same here

2024-05-19 15:18 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +            f"{countryball.description(include_emoji=True, bot=self.bot, is_trade=True)} "
and here

2024-05-19 15:18 UTC, flaree requested changes
small changes to be addressed

2024-06-06 14:06 UTC, laggron42 requested changes

2024-06-06 14:06 UTC, laggron42 commented on ballsdex/packages/balls/cog.py
> +            "to {user.mention}!"
I'm not sure what you did here? It looks the same as before, except you removed the `short` and `is_trade` arguments which make sense here.

You also forgot an `f` for your string, `{user.mention}` isn't processed at the last line

2024-08-30 10:52 UTC, closed without merging