fixed /player delete.
Ballsdex-Team/BallsDex-DiscordBot pull request #281
Opened 2024-06-12 08:05 UTC by Kingofthehill4965

I saw the bug report in the server that it does not show if the ball is traded if the user who gave that ball deletes their data afterwards. This should fix it since now only the instances the player owns are getting deleted and not all the player data. Please review

2024-06-26 12:54 UTC, laggron42 requested changes
Hey, thanks for the contribution!

However, this is not the right way to do things as we *need* the Player object to be deleted for GDPR purposes. What should be done instead is to modify the SQL schema such that deleting a row does not cascade over a trade model.

Sorry, I know it's annoying having to redo things, especially given how painful aerich can be, if you want I can walk you through this, I contacted you on Discord.

2024-07-02 05:43 UTC, Kingofthehill4965 commented
Hi... Sorry i couldn't respond earlier since I was travelling on vacation. I am free now and can respond as soon as possible

2024-08-21 17:34 UTC, Kowlin commented
Pending discussion on #346

2024-08-30 10:43 UTC, flaree commented
Hi there, we plan on making a soft delete functionality so I believe this PR will no longer be needed when that comes along.

We appreciate the work put in thus far.

2024-08-30 10:43 UTC, closed without merging