Add a currency along with various uses
Ballsdex-Team/BallsDex-DiscordBot pull request #296
Opened 2024-06-27 14:19 UTC by flaree

Adds a currency (configurable name in config).

TODO:

- [X] Add configurable currency and name.
- [X] Add rarity tiers and assignable value and coin amount.
- [X] Gain X coins on each countryball catch, depending on ball rarity.
- [X] Add `balls dispose` - dispose of a ball for 1/2 the worth.
- [X] Add `player balance` to view your balance.
- [] Add ability to use coins in trades.
- [] Wandering 'salesman' who will sell random countryballs, will be a random spawn similar to countryballs but rarer.

Future work for later additions:
- Achievements will give coins depending on their 'hardness'

2024-08-21 13:48 UTC, Kowlin requested changes
The issue from ``packages/trade/menu#L318`` has to be fixed before this can be merged.

2024-08-21 13:48 UTC, Kowlin commented on ballsdex/core/models.py
> +        await self.save(update_fields=("coins",))
``add_coins`` and ``remove_coins`` should probably return some output on its status as confirmation.

2024-08-21 13:48 UTC, Kowlin commented on ballsdex/packages/balls/cog.py
> +    async def dispose(self, interaction: discord.Interaction, ball: BallInstanceTransform):
Not sure if ``dispose`` is the best naming for this command, it seems a bit negative. perhaps ``exchange``

2024-08-21 13:48 UTC, Kowlin commented on ballsdex/packages/trade/cog.py
> +        if trader is None:
I think its time for a helper function to check for all these errors as this has been repeated over 4 times in the codebase now.

2024-08-21 13:48 UTC, Kowlin commented on ballsdex/packages/trade/menu.py
> +        if (
this **NEEDS** to be moved higher before the balls are saved. Otherwise we're gonna have situations where balls will be transferred but coins wouldn't!

2024-10-16 15:28 UTC, MaxxMXSZ commented
About the wandering trader it would be better to make a separate pr for it after coin have been merge. Mainly to evaluate how much members value the coin to give the set value for shops!

2024-10-27 14:34 UTC, imtherealF1 requested changes
this pr also breaks the trade display and that needs some fixes

2024-10-27 14:34 UTC, imtherealF1 commented on ballsdex/packages/balls/cog.py
> +        if ball.countryball.enabled or not ball.is_tradeable:
```suggestion
        if not ball.countryball.enabled or not ball.is_tradeable:
```

2024-10-27 14:34 UTC, imtherealF1 commented on ballsdex/packages/balls/cog.py
> +        await interaction.response.send_message(
```suggestion
        await interaction.followup.send(
```
the command wouldn't work otherwise

2024-10-27 14:34 UTC, imtherealF1 commented on ballsdex/packages/trade/cog.py
> +                    f"Total in proposal: {trader.coins} {settings.currency_name}.",
```suggestion
                    f"Added {amount} {settings.currency_name} to your proposal. "
                    f"Total in proposal: {trader.coins} {settings.currency_name}.",
```
just for correct grammar

2024-10-27 14:34 UTC, imtherealF1 commented on ballsdex/packages/trade/cog.py
> +                )
```suggestion
            if amount < 0:
                await interaction.response.send_message(
                    "You cannot add a number below 0 as the amount.", ephemeral=True
                )
                return
            if amount > await trader.fetch_player_coins():
                await interaction.response.send_message(
                    f"You don't have enough {settings.currency_name} to add that amount.",
                    ephemeral=True,
                )
                return
```
adding a check so that the amount can't be negative, and those messages as ephemeral

2024-10-27 14:34 UTC, imtherealF1 commented on ballsdex/settings.py
>  max-favorites: 50
```suggestion
# currency name, coins by default
currency-name: coins

# maximum amount of favorites that are allowed
max-favorites: 50
```
just adding a comment which makes it more obvious, to be honest when testing i didn't notice it at first

2024-10-27 14:34 UTC, imtherealF1 commented on ballsdex/settings.py
> +    settings.rarities = content.get("rarities", {})
```suggestion
    settings.rarities = content.get("rarities", {})
    settings.currency_name = content["currency-name"]
```
without this, having settings.currency_name in the config wouldn't do anything

2024-10-27 14:54 UTC, MaxxMXSZ commented
Putting this as DRAFT again, i will run through all the changes myself and fix some broken stuff.

2024-12-12 15:10 UTC, OLi51 commented
this is my idea :(

2024-12-12 16:20 UTC, imtherealF1 requested changes

2024-12-12 16:20 UTC, imtherealF1 commented on ballsdex/packages/admin/cog.py
> +        await player.add_coins(amount)
```suggestion
        await player.remove_coins(amount)
```
otherwise /remove adds coins

2024-12-12 16:20 UTC, imtherealF1 commented on ballsdex/packages/trade/cog.py
> +        if amount > await trader.fetch_player_coins():
```suggestion
        if amount > await trader.fetch_player_coins() - trader.coins:
```
otherwise you can exploit the commnand

2024-12-12 16:20 UTC, imtherealF1 commented on ballsdex/packages/trade/menu.py
> +
```suggestion
            await countryball.unlock()
```
this shouldn't be there, otherwise a user can just add 500 coins, cancel the trade and get the coins from his own proposal back

2024-12-12 16:26 UTC, imtherealF1 commented
also, if config.yml isn't updated hence no rarities, /dispose will give a `KeyError: 'legendary'`, and in general `settings.rarities = content.get("rarities", {})` doesnt work

2024-12-13 15:14 UTC, laggron42 commented
> this is my idea :(

@OLi51 This was considered since before Ballsdex was even released to the public. We haven't looked for any fork or other code for getting inspirations (unless they bring it up to us as suggestions), and besides it's not hard to get that kind of idea.

I don't really understand the goal of your comment? You don't have any code uploaded, there's no contribution from you. If you want to add features, you are free and welcome to open pull requests, then you'll be properly credited. I find it kinda sad to see people developing private features for themselves and wanting exclusivity, when I want to encourage sharing and contributions, that's why the bot is open source to begin with.

2024-12-17 16:04 UTC, laggron42 commented on ballsdex/packages/trade/menu.py
> +        self.initial_coins_trader2 = trader2.coins
These attributes are unused

2025-02-19 13:33 UTC, flaree commented
splitting up into further PRs

2025-02-19 13:33 UTC, closed without merging