beginning work on friends
Ballsdex-Team/BallsDex-DiscordBot pull request #340
Opened 2024-08-19 15:05 UTC by imtherealF1

2024-09-10 09:30 UTC, flaree requested changes

2024-09-10 09:30 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +            )
The ball should be unlocked here

2024-09-10 09:30 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +    friendship = await Friendship.filter(
Can this be moved into the elif and also use the function added to player model

2024-09-10 09:30 UTC, flaree commented on ballsdex/packages/players/cog.py
> +                "You cannot add a blocked user. To unblock, use `/player unblock`.",
Is it possible to use the command mention here, 

ie: self.cog.add.extras.get("mention", "`/player unblock`")

2024-09-10 09:30 UTC, flaree commented on ballsdex/packages/players/cog.py
> +    async def list(self, interaction: discord.Interaction):
```suggestion
    @friend.command(name="list")
    async def friend_list(self, interaction: discord.Interaction):
```

Using the same function names can result in some weird errors/handling, this should be done for all where the func names overlap



ie: add, remove and list for friend and block

2024-09-10 11:54 UTC, flaree requested changes

2024-09-10 11:54 UTC, flaree commented on ballsdex/packages/players/cog.py
> +            await Friendship.create(player1=player1, player2=player2)
We should confirm with the other user if they want to be friends, right now this is forcing a friendship. 
IE: user1 friends user2, user 2 doesnt have a choice but not it forcefully appears within his friend list

2024-09-10 11:54 UTC, flaree commented on ballsdex/packages/players/cog.py
> +    async def block(self, interaction: discord.Interaction, user: discord.User):
```suggestion
    @blocked.command(name="add")
    async def block_add(self, interaction: discord.Interaction, user: discord.User):
```

Should be using the block subcommand here

2024-09-10 11:54 UTC, flaree commented on ballsdex/packages/players/cog.py
> +            await interaction.response.send_message("You haven't got any friends!", ephemeral=True)
This seems a bit harsh of wording,

how does "You currently do not have any friends added." sound?

2024-09-10 12:22 UTC, imtherealF1 commented on ballsdex/packages/players/cog.py
> +            await interaction.response.send_message("You haven't got any friends!", ephemeral=True)
sounds a lot better than "you havent got any friends"

2024-09-12 20:54 UTC, flaree commented on ballsdex/packages/players/cog.py
> +        )
This query also shows if a user has you blocked, it should be changed for just 
```suggestion
        blocked_relations = (
            await Block.filter(player1=player)
            .select_related("player1", "player2")
            .all()
        )
```
this way its only people that player1 has blocked, aka the person invoking

2024-09-12 21:08 UTC, flaree requested changes

2024-09-12 21:08 UTC, flaree commented on ballsdex/packages/players/cog.py
> +            app_commands.Choice(name="Friends Only", value=PrivacyPolicy.FRIENDS),
```suggestion
            app_commands.Choice(name="Friends Only", value=PrivacyPolicy.FRIENDS),
            app_commands.Choice(name="Same Server", value=PrivacyPolicy.SAME_SERVER),
```

if members intent is disabled, we pop the final option from this set of choices (which before was same server) so when a new option was added at the end it was getting rid of that instead of same server. Changing the order fixes this

2024-09-12 21:08 UTC, flaree commented on ballsdex/packages/balls/cog.py
> +                "This user's inventory can only be viewed from users they have added as friends.",
```suggestion
                "This users inventory can only be viewed from users they have added as friends.",
```

2024-09-12 21:13 UTC, flaree commented
this pr also breaks help, will that be fixed in this PR or a seperate?

2024-09-13 10:48 UTC, imtherealF1 commented
> this pr also breaks help, will that be fixed in this PR or a seperate?

id rather do a new pr, preparing that now

2024-09-13 13:13 UTC, flaree commented on ballsdex/packages/players/cog.py
> +        blocked = await player1.is_blocked(player2)
if player1 blocks player2, player2 cannot block player1

2024-09-13 13:14 UTC, flaree commented on ballsdex/core/models.py
> +        ).exists()
```suggestion
        return await Friendship.filter(
            (Q(player1=self) & Q(player2=other_player))
        ).exists()
```

the prev comment should be resolved with this

2024-09-13 13:16 UTC, flaree commented on ballsdex/packages/players/cog.py
> +            ).delete()
```suggestion
            await Block.filter(
                (Q(player1=player1) & Q(player2=player2))
            ).delete()
```

2024-09-13 13:41 UTC, flaree approved these changes

2024-09-13 13:41 UTC, merged