adding interaction check to config embed, making channel optional, and some logic changes
Ballsdex-Team/BallsDex-DiscordBot pull request #350
Opened 2024-08-22 10:55 UTC by imtherealF1

2024-08-22 11:23 UTC, flaree commented on ballsdex/packages/config/cog.py
> +            if not channel.permissions_for(guild.me).read_messages:
https://discordpy.readthedocs.io/en/stable/interactions/api.html?highlight=has_permission#discord.app_commands.checks.has_permissions


These checks can be done in the decorator to save having repeated logic

2024-08-22 11:25 UTC, flaree commented on ballsdex/packages/config/components.py
> +        channel: discord.TextChannel,
What's the need for the player object here? Just pass the discord.Member object instead directly from the invoked of the command

2024-08-22 11:25 UTC, flaree requested changes
Couple changes to reduce repeated code and some other issues

2024-08-22 12:05 UTC, imtherealF1 commented on ballsdex/packages/config/cog.py
> +            if not channel.permissions_for(guild.me).read_messages:
@flaree when testing @app_commands.checks.bot_has_permissions(read_messages=True, send_messages=True, embed_links=True), i realised that when the bot doesnt have the permissions required, it responds with "You are not allowed to use this command", which doesnt state what the issue is. should i keep that or should i change it

2024-08-22 12:24 UTC, flaree commented on ballsdex/packages/config/cog.py
> +            if not channel.permissions_for(guild.me).read_messages:
That's fine for now, i'll create a separate issue to handle permission checks correctly

2024-08-22 14:15 UTC, flaree commented on ballsdex/packages/config/cog.py
> +        The new text channel to set.
I think the previous description is more apt, there's no context as to what you want to set here

2024-08-22 14:15 UTC, flaree commented on ballsdex/packages/config/cog.py
> +                channel = cast(discord.TextChannel, interaction.channel)
What's the use of this casting, your isinstance check is True meaning it already is a TextChannel

2024-08-22 14:15 UTC, flaree commented on ballsdex/packages/config/cog.py
> +        if channel and isinstance(channel, discord.TextChannel):
May be better to separate the handling of the instance check out instant of having it in this if and elif

2024-08-29 19:05 UTC, ltzmax commented on ballsdex/packages/config/components.py
> +                pass
the `self.stop()` is not really needed
```suggestion
    async def on_timeout(self) -> None:
        if self.message:
            for item in self.children:
                item: discord.ui.Button
                item.disabled = True
            try:
                await self.message.edit(view=self)
            except discord.HTTPException:
                pass
```

2024-08-30 17:41 UTC, flaree approved these changes

2024-08-30 17:42 UTC, merged