Added phrases customizability
Ballsdex-Team/BallsDex-DiscordBot pull request #386
Opened 2024-09-04 20:48 UTC by MaxxMXSZ

Made a new pr since can't be bothered to resolve the conflict. this closes #299

2024-09-19 10:14 UTC, ltzmax reviewed
Should we also add catchphrase for shiny? Since i've seen people edit this so could be good too.

2024-09-23 20:54 UTC, MaxxMXSZ commented
> Should we also add catchphrase for shiny? Since i've seen people edit this so could be good too.

Indeed would be useful will get it done later tomorrow

2024-09-24 21:24 UTC, ltzmax requested changes

2024-09-24 21:24 UTC, ltzmax commented on ballsdex/packages/countryballs/components.py
> +            await interaction.response.send_message(
You gotta add back `await interaction.followup.send`. its from #430.

2024-09-24 21:24 UTC, ltzmax commented on ballsdex/packages/countryballs/components.py
> -            await interaction.response.send_message("I was caught already!", ephemeral=True)
Same here, gotta add back, related to #430.

2024-09-26 09:47 UTC, ltzmax requested changes

2024-09-26 09:47 UTC, ltzmax commented on ballsdex/settings.py
> +shiny-phrase: ✨ ***It's a shiny {settings.collectible_name}!***
```suggestion
# override the phrase "✨ ***It's a shiny {collectible_name}!*** ✨"
# NOTE THAT you MUST include {collectible_name} somewhere in the phrase
shiny-phrase: ✨ ***It's a shiny {collectible_name}!***
```

2024-09-26 09:47 UTC, ltzmax commented on ballsdex/settings.py
> +shiny-phrase: ✨ ***It's a shiny {settings.collectible_name}!***
```suggestion
# override the phrase "✨ ***It's a shiny {collectible_name}!*** ✨"
# NOTE THAT you MUST include {collectible_name} somewhere in the phrase
shiny-phrase: ✨ ***It's a shiny {collectible_name}!***
```

2024-09-29 18:46 UTC, ltzmax approved these changes
Looks good now. and it was already reviewed by flare on your previous pr on most part so we're good here.

2024-09-30 22:04 UTC, ltzmax requested changes
Well good we didn't merge yet. 
When we mistype the collectible_name, it'd actually just send errors + when the text is empty, it'd also happen. Maybe have a default text instead of None? just in case or something, @laggron42 maybe have better solutions to this!
```py
bot-1              | 2024-09-30 21:47:59 ERROR    ballsdex.core.bot Error in slash command spawn
bot-1              | Traceback (most recent call last):
bot-1              |   File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 857, in _do_call
bot-1              |     return await self._callback(self.binding, interaction, **params)  # type: ignore
bot-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1              |   File "/code/ballsdex/packages/admin/cog.py", line 534, in spawn
bot-1              |     result = await ball.spawn(channel or interaction.channel)  # type: ignore
bot-1              |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1              |   File "/code/ballsdex/packages/countryballs/countryball.py", line 60, in spawn
bot-1              |     f"{settings.wild_phrase.format(collectible_name=settings.collectible_name)}",
bot-1              |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1              | AttributeError: 'NoneType' object has no attribute 'format'
```

2024-10-12 22:46 UTC, MaxxMXSZ commented
laggron seems to have a better solution i will leave this to him

2024-10-12 22:46 UTC, closed without merging