[player] adding /player friend policy
Ballsdex-Team/BallsDex-DiscordBot pull request #406
Opened 2024-09-13 15:30 UTC by imtherealF1

2024-09-13 19:23 UTC, ltzmax requested changes

2024-09-13 19:23 UTC, ltzmax commented on ballsdex/packages/players/cog.py
> +            app_commands.Choice(name="Deny all friend requests", value=MentionPolicy.DENY),
This needs to be changed as it uses the same as mentions.
```suggestion
            app_commands.Choice(name="Accept all friend requests", value=FriendPolicy.ALLOW),
            app_commands.Choice(name="Deny all friend requests", value=FriendPolicy.DENY),
```

2024-09-13 19:30 UTC, imtherealF1 commented on ballsdex/packages/players/cog.py
> +            app_commands.Choice(name="Deny all friend requests", value=MentionPolicy.DENY),
dumb mistake on my part sorry

2024-09-15 23:10 UTC, ltzmax approved these changes

2024-09-15 23:23 UTC, merged