[info] making the /tutorial command
Ballsdex-Team/BallsDex-DiscordBot pull request #432
Opened 2024-09-30 19:48 UTC by imtherealF1

2024-10-26 14:07 UTC, ltzmax requested changes
i think this can be used on ballsdex.com/tutorial instead of making something like this but that's me.

2024-10-26 14:07 UTC, ltzmax commented on ballsdex/packages/info/cog.py
> +                f"{config_channel}. You must have the `Manage Guild` permission in that server."
I dont think we need to mention in the current server, so it'd be better this way instead.
```suggestion
                f"{config_channel}. You must have the ``Manage Guild`` "
                "permission to use this command."
```

2024-10-26 16:33 UTC, imtherealF1 commented
it can, but since the source code for the website isn't here i just decided to do it like this for now

2024-10-26 17:28 UTC, ltzmax commented on ballsdex/packages/info/cog.py
> +                f"{config_channel}. You must have the `Manage Guild` permission."
Still should say `to use this command` after permission, its more clear, because of our community base.

2025-01-01 17:11 UTC, imtherealF1 commented
closing this too, ill reopen a new branch

2025-01-01 17:12 UTC, closed without merging