[settings] move packages to settings
Ballsdex-Team/BallsDex-DiscordBot pull request #472
Opened 2024-11-28 00:03 UTC by Dotsian

This change makes it easier for self-hosted owners to add custom packages (without having to modify the bot.py file).

2024-11-28 11:06 UTC, flaree commented
While this is a great idea, I foresee issues in the future should we add more cogs to the base bot as it won't be propagated to everyone's configs downstream

2024-11-28 14:50 UTC, laggron42 commented
Haha you got forward of me, this is actually a change I've planned to do but a little differently, by using full importable paths instead (like `ballsdex.packages.trade`). This would allow 3rd party cogs to exist in their own pip-installable repositories, thus allowing users to install additional cogs without having to manually drop files or edit code.

Do you think you could change the PR to reflect that? You'd also need to remove the prepended path [here](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/blob/6a7e88b5132a571f8d36c83b20cf22df3e31a608/ballsdex/core/bot.py#L309).

> While this is a great idea, I foresee issues in the future should we add more cogs to the base bot as it won't be propagated to everyone's configs downstream

I can still think of ways to dynamically extend the list of cogs after this change. Not trivial, but doable, and the benefits are really nice.

2024-11-29 10:39 UTC, laggron42 commented
Thanks for the change, I'll test it as soon as possible but it already looks good on a first glance

2024-12-02 20:16 UTC, laggron42 requested changes
I tested the PR and had to do the following changes to get it to work as intended. Apply as needed and I can merge

2024-12-02 20:16 UTC, laggron42 commented on ballsdex/core/bot.py
> +            package_name = package.split(".")[-1]
I like this better, it doesn't hide the full path for custom packages
```suggestion
            package_name = package.replace("ballsdex.packages.", "")
```

2024-12-02 20:16 UTC, laggron42 commented on ballsdex/core/bot.py
> +        if "admin" in settings.packages:
Doesn't sync without the full path
```suggestion
        if "ballsdex.packages.admin" in settings.packages:
```

2024-12-02 20:16 UTC, laggron42 commented on ballsdex/settings.py
> +    settings.packages = content["packages"] or []
Because of odd design, the content of the yaml is read before update, so you need to handle the case where the list doesn't exist yet
```suggestion
    settings.packages = content.get("packages") or [
        "ballsdex.packages.admin",
        "ballsdex.packages.balls",
        "ballsdex.packages.config",
        "ballsdex.packages.countryballs",
        "ballsdex.packages.info",
        "ballsdex.packages.players",
        "ballsdex.packages.trade",
    ]
```

2024-12-02 20:16 UTC, laggron42 commented on ballsdex/settings.py
> +    add_packages = "packages" not in content
Won't be detected otherwise as "ballsdex.packages.countryballs.spawn.SpawnManager" already exists in the default config
```suggestion
    add_packages = "packages:" not in content
```

2024-12-02 21:41 UTC, Dotsian commented
> I tested the PR and had to do the following changes to get it to work as intended. Apply as needed and I can merge

Hi, I couldn't test the PR because I was out for the holidays. I just resolved all the changes requested 🙂

2024-12-03 10:07 UTC, laggron42 approved these changes
Tested and works for me, thanks a lot for the contribution!

2024-12-03 10:07 UTC, merged