models: remove shinies, replace by pre-made special
Ballsdex-Team/BallsDex-DiscordBot pull request #478
Opened 2024-12-02 19:31 UTC by laggron42

This is taken from #436 but as a separate PR, since it's a change that would be very benefical in general, doesn't need to wait for the other stuff from that PR to be ready

2024-12-03 14:01 UTC, flaree requested changes

2024-12-03 14:01 UTC, flaree commented on migrations/models/36_20241009120300_update.sql
> +ALTER TABLE "special" ALTER COLUMN "end_date" SET NOT NULL;
Receiving a `asyncpg.exceptions.PostgresSyntaxError: syntax error at end of input` when attempting to run the migration, no other information is present.

2024-12-10 15:52 UTC, laggron42 commented on migrations/models/36_20241009120300_update.sql
> +ALTER TABLE "special" ALTER COLUMN "end_date" SET NOT NULL;
Can you try again now?

2024-12-30 15:09 UTC, flaree commented
needs conflict resolved

2025-01-01 15:03 UTC, flaree approved these changes

2025-01-01 15:03 UTC, merged